# Generated by Django 5.2.15 on 2026-06-12 11:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spedizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('da_cliente_citta', models.CharField(max_length=200)),
                ('a_cliente_citta', models.CharField(max_length=200)),
                ('se_triangolazione', models.BooleanField(default=False)),
                ('contrassegno_euro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('assicurazione_euro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peso_totale_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trasportatore_scelto', models.CharField(blank=True, max_length=100, null=True)),
                ('valore_preventivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Spedizioni',
            },
        ),
        migrations.CreateModel(
            name='Spedizioniere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_tariffazione', models.CharField(choices=[('scaglioni', 'Scaglioni'), ('collo', 'A collo')], default='scaglioni', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Spedizionieri',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Zone',
            },
        ),
        migrations.CreateModel(
            name='Pacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altezza_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('larghezza_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('profondita_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('spedizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacchi', to='trasporti.spedizione')),
            ],
            options={
                'verbose_name_plural': 'Pacchi',
            },
        ),
        migrations.CreateModel(
            name='Supplemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('calc_type', models.CharField(choices=[('fisso', 'fisso'), ('percentuale', 'percentuale')], max_length=28)),
                ('applic_type', models.CharField(choices=[('a collo', 'a collo'), ('a spedizione', 'a spedizione')], max_length=28)),
                ('valore', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('spedizioniere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trasporti.spedizioniere')),
            ],
            options={
                'verbose_name_plural': 'Supplementi',
            },
        ),
        migrations.AddField(
            model_name='spedizione',
            name='a_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_zona', to='trasporti.zona'),
        ),
        migrations.AddField(
            model_name='spedizione',
            name='da_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dazona', to='trasporti.zona'),
        ),
        migrations.CreateModel(
            name='Zona_spedizioniere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisore_volumetrico', models.IntegerField(default=5000)),
                ('peso_minimo_fatturabile', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contrassegno_allowed', models.BooleanField(default=False)),
                ('spedizioniere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trasporti.spedizioniere')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trasporti.zona')),
            ],
            options={
                'verbose_name_plural': 'Zone Spedizionieri',
                'unique_together': {('spedizioniere', 'zona')},
            },
        ),
        migrations.CreateModel(
            name='Scaglione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('spedizioniere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trasporti.spedizioniere')),
                ('zona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trasporti.zona')),
                ('zona_spedizioniere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trasporti.zona_spedizioniere')),
            ],
            options={
                'verbose_name_plural': 'Scaglioni',
            },
        ),
        migrations.CreateModel(
            name='OverflowTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_step', models.DecimalField(decimal_places=2, max_digits=8)),
                ('zona_spedizioniere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trasporti.zona_spedizioniere')),
            ],
            options={
                'verbose_name_plural': 'Tariffe extra soglia (non in scaglioni)',
            },
        ),
    ]
