# Generated by Django 5.2.15 on 2026-06-11 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spedizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da_cliente_citta', models.CharField(max_length=200)),
                ('a_cliente_citta', models.CharField(max_length=200)),
                ('se_triangolazione', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Zone',
            },
        ),
        migrations.CreateModel(
            name='Pacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altezza_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('larghezza_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('profondita_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('spedizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacchi', to='trasporti.spedizione')),
            ],
        ),
        migrations.AddField(
            model_name='spedizione',
            name='a_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_zona', to='trasporti.zona'),
        ),
        migrations.AddField(
            model_name='spedizione',
            name='da_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dazona', to='trasporti.zona'),
        ),
    ]
