# Generated by Django 5.2.15 on 2026-06-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacco',
            options={'verbose_name_plural': 'Pacchi'},
        ),
        migrations.AlterModelOptions(
            name='spedizione',
            options={'verbose_name_plural': 'Spedizioni'},
        ),
        migrations.AddField(
            model_name='spedizione',
            name='peso_totale_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
