# Generated by Django 5.2.15 on 2026-06-12 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zona_spedizioniere',
            options={'verbose_name_plural': 'Zone Tariffazione Spedizionieri'},
        ),
        migrations.AddField(
            model_name='spedizione',
            name='zona_tariffazione_spedizioniere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zona_tariffazione_spedizioniere', to='trasporti.zona_spedizioniere'),
            preserve_default=False,
        ),
    ]
