# Generated by Django 5.2.15 on 2026-06-12 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0002_alter_zona_spedizioniere_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overflowtariff',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='overflowtariff',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
