# Generated by Django 5.2.15 on 2026-06-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0002_alter_pacco_options_alter_spedizione_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spedizione',
            name='trasportatore_scelto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spedizione',
            name='valore_preventivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
