# Generated by Django 5.2.15 on 2026-06-12 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0003_overflowtariff_valid_from_overflowtariff_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='spedizione',
            name='trasportatore_sceltoFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trasporti.spedizioniere'),
        ),
    ]
