# Generated by Django 5.2.15 on 2026-06-11 20:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0003_spedizione_trasportatore_scelto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spedizione',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
