# Generated by Django 5.2.15 on 2026-06-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0004_spedizione_trasportatore_sceltofk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spedizione',
            name='trasportatore_scelto',
        ),
    ]
