# Generated by Django 5.2.15 on 2026-06-11 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0004_spedizione_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spedizione',
            name='data',
            field=models.DateField(default=datetime.date(2026, 6, 11)),
        ),
    ]
