# Generated by Django 5.2.15 on 2026-06-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0005_alter_spedizione_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='spedizione',
            name='assicurazione_euro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='spedizione',
            name='contrassegno_euro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
