# Generated by Django 5.2.15 on 2026-06-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0005_remove_spedizione_trasportatore_scelto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spedizione',
            old_name='trasportatore_sceltoFK',
            new_name='trasportatore_scelto',
        ),
    ]
