# Generated by Django 5.2.15 on 2026-06-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0006_rename_trasportatore_sceltofk_spedizione_trasportatore_scelto'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplemento',
            name='applica_fuel',
            field=models.BooleanField(default=True),
        ),
    ]
