# Generated by Django 5.2.15 on 2026-06-12 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0007_supplemento_applica_fuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='spedizione',
            name='se_triangolazione',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='spedizione',
            name='servizi_richiesti',
            field=models.ManyToManyField(blank=True, to='trasporti.tiposervizio'),
        ),
        migrations.AddField(
            model_name='supplemento',
            name='tipo_servizio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplementi_corrieri', to='trasporti.tiposervizio'),
        ),
    ]
