# Generated by Django 5.2.15 on 2026-06-12 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0008_tiposervizio_alter_spedizione_se_triangolazione_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spedizione',
            name='se_triangolazione',
        ),
    ]
