# Generated by Django 5.2.15 on 2026-06-13 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0009_remove_spedizione_se_triangolazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplemento',
            name='zona_spedizioniere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplementi', to='trasporti.zona_spedizioniere'),
        ),
    ]
