# Generated by Django 5.2.15 on 2026-06-13 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0010_supplemento_zona_spedizioniere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplemento',
            name='spedizioniere',
        ),
    ]
