# Generated by Django 5.2.15 on 2026-06-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0012_remove_supplemento_zona_spedizioniere'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplemento',
            name='zone_tariffazione',
            field=models.ManyToManyField(blank=True, help_text='Seleziona le zone in cui questo supplemento è applicabile. Se vuoto, non verrà applicato.', related_name='supplementi', to='trasporti.zona_spedizioniere'),
        ),
    ]
