# Generated by Django 5.2.15 on 2026-06-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0013_supplemento_zone_tariffazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spedizione',
            name='peso_totale_kg',
        ),
    ]
