# Generated by Django 5.2.15 on 2026-06-13 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0014_remove_spedizione_peso_totale_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='spedizione',
            name='zona_tariffazione_spedizioniere2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spedizioni', to='trasporti.zona_spedizioniere'),
        ),
    ]
