# Generated by Django 5.2.15 on 2026-06-13 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0015_spedizione_zona_tariffazione_spedizioniere2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spedizione',
            name='zona_tariffazione_spedizioniere2',
        ),
        migrations.AlterField(
            model_name='spedizione',
            name='zona_tariffazione_spedizioniere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spedizioni', to='trasporti.zona_spedizioniere'),
        ),
    ]
