# Generated by Django 5.2.15 on 2026-06-13 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0016_remove_spedizione_zona_tariffazione_spedizioniere2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona_spedizioniere',
            name='zone_comprese',
            field=models.ManyToManyField(help_text='Seleziona tutte le zone che partecipano a questa tariffa (es: Italia, Spagna, Svizzera)', related_name='zone_tariffazione_spedizionieri', to='trasporti.zona'),
        ),
        migrations.CreateModel(
            name='MappaturaZonaTariffaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato_partenza', models.CharField(help_text='Es: Italia', max_length=100)),
                ('stato_destinazione', models.CharField(help_text='Es: Spagna, Svizzera, Italia', max_length=100)),
                ('zona_corrispondente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappature_tariffarie', to='trasporti.zona')),
            ],
            options={
                'verbose_name': 'Mappatura Zona Tariffaria',
                'verbose_name_plural': 'Mappature Zone Tariffarie',
            },
        ),
    ]
