# Generated by Django 5.2.15 on 2026-06-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0017_zona_spedizioniere_zone_comprese_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zona_spedizioniere',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='zona_spedizioniere',
            name='zone_comprese',
        ),
        migrations.RemoveField(
            model_name='zona_spedizioniere',
            name='zona',
        ),
        migrations.AddField(
            model_name='zona_spedizioniere',
            name='zona',
            field=models.ManyToManyField(help_text='Seleziona tutte le zone che partecipano a questa tariffa (es: Italia, Spagna, Svizzera)', related_name='zone_tariffazione_spedizionieri', to='trasporti.zona'),
        ),
    ]
