# Generated by Django 5.2.15 on 2026-06-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0018_alter_zona_spedizioniere_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona_spedizioniere',
            name='zona',
            field=models.ManyToManyField(help_text='Seleziona le zone che sono servite questa tariffa', related_name='zone_tariffazione_spedizionieri', to='trasporti.zona'),
        ),
    ]
