# Generated by Django 5.2.15 on 2026-06-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0019_alter_zona_spedizioniere_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona_spedizioniere',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
