# Generated by Django 5.2.15 on 2026-06-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0020_zona_spedizioniere_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scaglione',
            name='zona',
        ),
    ]
