# Generated by Django 5.2.15 on 2026-06-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0021_remove_scaglione_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplemento',
            name='valore_minimo',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimo applicabile (es. 5.00 euro)', max_digits=10),
        ),
    ]
