# Generated by Django 5.2.15 on 2026-06-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0022_supplemento_valore_minimo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplemento',
            old_name='valore_minimo',
            new_name='diritto_minimo_euro',
        ),
    ]
