# Generated by Django 5.2.15 on 2026-06-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0023_rename_valore_minimo_supplemento_diritto_minimo_euro'),
    ]

    operations = [
        migrations.AddField(
            model_name='spedizione',
            name='supplementi',
            field=models.ManyToManyField(blank=True, to='trasporti.supplemento'),
        ),
    ]
