# Generated by Django 5.2.15 on 2026-06-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0024_spedizione_supplementi'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona_spedizioniere',
            name='priorita',
            field=models.IntegerField(default=0, help_text='Più alto è il numero, più è specifica la zona.'),
        ),
    ]
