# Generated by Django 5.2.15 on 2026-06-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0025_zona_spedizioniere_priorita'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona_spedizioniere',
            name='divisore_volumetrico_light',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zona_spedizioniere',
            name='peso_soglia_light',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
