# Generated by Django 5.2.15 on 2026-06-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0026_zona_spedizioniere_divisore_volumetrico_light_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spedizione',
            name='a_cliente_citta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spedizione',
            name='da_cliente_citta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
