# Generated by Django 5.2.15 on 2026-06-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0027_alter_spedizione_a_cliente_citta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposervizio',
            options={'verbose_name_plural': 'Mappatura Supplementi (Tipo Servizi)'},
        ),
    ]
