# Generated by Django 5.2.15 on 2026-06-14 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0028_alter_tiposervizio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scaglione',
            name='spedizioniere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spedizioniere', to='trasporti.spedizioniere'),
        ),
        migrations.AlterField(
            model_name='scaglione',
            name='zona_spedizioniere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zona_spedizioniere', to='trasporti.zona_spedizioniere'),
        ),
        migrations.AlterField(
            model_name='spedizione',
            name='da_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='da_zona', to='trasporti.zona'),
        ),
        migrations.AlterField(
            model_name='spedizione',
            name='trasportatore_scelto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trasportatore_scelto', to='trasporti.spedizioniere'),
        ),
        migrations.AlterField(
            model_name='zona_spedizioniere',
            name='zona',
            field=models.ManyToManyField(help_text='Seleziona le zone che sono servite questa tariffa', related_name='zone_spedizioniere', to='trasporti.zona'),
        ),
    ]
