# Generated by Django 5.2.15 on 2026-06-14 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0029_alter_scaglione_spedizioniere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona_spedizioniere',
            name='spedizioniere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sspedizioniere', to='trasporti.spedizioniere'),
        ),
    ]
