# Generated by Django 5.2.15 on 2026-06-16 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0031_profilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilo',
            name='righe_per_pagina',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='zona_spedizioniere',
            name='divisore_volumetrico',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='zona_spedizioniere',
            name='divisore_volumetrico_light',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zona_spedizioniere',
            name='priorita',
            field=models.PositiveIntegerField(default=0, help_text='Più alto è il numero, più è specifica la zona.'),
        ),
        migrations.CreateModel(
            name='Tariffa_colli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('colli_quantità_da', models.PositiveIntegerField(default=0)),
                ('colli_quantità_a', models.PositiveIntegerField(default=0)),
                ('costo_euro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spedizioniere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spedizioniere_Tc', to='trasporti.spedizioniere')),
                ('zona_spedizioniere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zona_spedizioniere_Tc', to='trasporti.zona_spedizioniere')),
            ],
            options={
                'verbose_name_plural': 'Tariffe a collo',
            },
        ),
    ]
