# Generated by Django 5.2.15 on 2026-06-16 20:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0032_alter_profilo_righe_per_pagina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariffa_colli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('colli_quantità_da', models.PositiveIntegerField(default=0)),
                ('colli_quantità_a', models.PositiveIntegerField(default=0)),
                ('costo_euro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spedizioniere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='spedizioniere_Tc', to='trasporti.spedizioniere')),
                ('zona_spedizioniere',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zona_spedizioniere_Tc',
                                   to='trasporti.zona_spedizioniere')),
            ],
        )
    ]
