# Generated by Django 5.2.15 on 2026-06-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trasporti", "0033_create_tariffa_colli_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tariffa_colli",
            options={"verbose_name_plural": "Tariffe a collo"},
        ),
    ]
