# Generated by Django 5.2.15 on 2026-06-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasporti', '0035_prova'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplemento',
            name='valore',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
