# Generated by Django 5.2.15 on 2026-06-20 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdineImportazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine_fornitore_sigla', models.CharField(blank=True, max_length=2, null=True)),
                ('ordine_nome_fornitore', models.CharField(blank=True, max_length=50, null=True)),
                ('ordine_num_pezzi', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('ordine_preventivo_dollari', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('ordine_proforma_arrivata_dollari', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('ordine_preventivi_nolo_import', models.TextField(blank=True, null=True)),
                ('ordine_confermata_spedizione_con_spedizioniere', models.CharField(blank=True, max_length=30, null=True)),
                ('arrivo_data', models.DateField(blank=True, null=True)),
                ('arrivo_num', models.PositiveIntegerField(blank=True, null=True)),
                ('ft_dazi_iva_ragione_sociale', models.CharField(blank=True, max_length=30, null=True)),
                ('ft_dazi_iva_iva_euro', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('ft_dazi_iva_dazio_euro', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('ft_dazi_iva_costi_accessori_euro', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('ft_dazi_iva_totale', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('ft_merce_fornit_sigla', models.CharField(blank=True, max_length=2, null=True)),
                ('ft_merce_fornit_ragione_sociale', models.CharField(blank=True, max_length=50, null=True)),
                ('ft_merce_num', models.CharField(blank=True, max_length=30, null=True)),
                ('ft_merce_data', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ft_merce_tot_pz', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('ft_valore_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('nolo_se_prepagato_in_ft_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('nolo_vettore_nome', models.CharField(blank=True, max_length=30, null=True)),
                ('nolo_ft_totale', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('ader_bolla_doganale_classica', models.BooleanField(default=False)),
                ('ader_MRN_codice', models.CharField(blank=True, max_length=30, null=True)),
                ('ader_stampato_mrn_da_ader', models.BooleanField(default=False)),
                ('ader_nostro_prot_num', models.CharField(blank=True, max_length=6, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('data', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('banca', models.CharField(blank=True, max_length=3, null=True)),
                ('ordine_importazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acconti', to='importPRC.ordineimportazione')),
            ],
        ),
    ]
