# Generated by Django 5.2.15 on 2026-06-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importPRC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordineimportazione',
            name='arrivo_anno',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
