# Generated by Django 5.2.15 on 2026-06-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importPRC', '0002_ordineimportazione_arrivo_anno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordineimportazione',
            old_name='nolo_ft_totale',
            new_name='nolo_ft_totale',
        ),
        migrations.AddField(
            model_name='ordineimportazione',
            name='ft_dazi_iva_totale_nostro_prot_numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ordineimportazione',
            name='nolo_ft_nostro_prot_numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
