# Generated by Django 5.2.15 on 2026-06-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importPRC', '0003_rename_nolo_tot_ft_ordineimportazione_nolo_ft_totale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordineimportazione',
            name='ft_merce_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
