# Generated by Django 5.2.15 on 2026-06-20 23:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importPRC', '0004_alter_ordineimportazione_ft_merce_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordineimportazione',
            name='ordine_data',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
