# Generated by Django 5.2.15 on 2026-06-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importPRC', '0005_ordineimportazione_ordine_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acconto',
            options={'verbose_name_plural': 'Acconti'},
        ),
        migrations.AlterModelOptions(
            name='ordineimportazione',
            options={'verbose_name_plural': 'Righe Ordini Importazioni'},
        ),
        migrations.AddField(
            model_name='ordineimportazione',
            name='ordine_descrizione',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
